--CREATE DATABASE TravelTourist;
--GO
USE TravelTourist;
GO 
CREATE TABLE DIEMTQ(
	MaDTQ VARCHAR(3) PRIMARY KEY, 
	TenDTQ NVARCHAR(100), 
	Noidung NVARCHAR(100), 
	Ynghia NVARCHAR(100)
)
CREATE TABLE TOUR(
	MaTour VARCHAR(3) PRIMARY KEY, 
	TenTour NVARCHAR(100), 
	Songay INT, 
	Sodem INT
)
CREATE TABLE CT_THAMQUAN (
    MaTour VARCHAR(3), 
    MaDTQ VARCHAR(3), 
    Thoigian INT, 
    CONSTRAINT FK_CT_Tour FOREIGN KEY(MaTour) REFERENCES TOUR(MaTour),
    CONSTRAINT FK_CT_DTQ FOREIGN KEY(MaDTQ) REFERENCES DIEMTQ(MaDTQ),
    CONSTRAINT PK_CT_TQ PRIMARY KEY (MaTour, MaDTQ)
);
CREATE TABLE DOAN(
	MaDoan VARCHAR(5) PRIMARY KEY,  
	HoTen NVARCHAR(30), 
	Phai NVARCHAR(3), 
	Ngaysinh DATE, 
	Diachi NVARCHAR(25), 
	Dienthoai VARCHAR(11)
)
CREATE TABLE HOPDONG (
	SoHD VARCHAR(5), 
	NgaylapHD DATE, 
	NoidungHD NVARCHAR(100), 
	SoNguoidi INT, 
	Noidon VARCHAR(10), 
	NgaydiHD DATE, 
	MaTour VARCHAR(3), 
	MaDoan VARCHAR(5),
	CONSTRAINT FK_HD_Tour FOREIGN KEY(MaTour) REFERENCES TOUR(MaTour),
	CONSTRAINT FK_HD_DOAN FOREIGN KEY(MaDoan) REFERENCES DOAN(MaDoan),
	CONSTRAINT PK_HD PRIMARY KEY (SoHD)
)
CREATE TABLE DIEMDUNGCHAN(
	MaDDC VARCHAR(5) PRIMARY KEY, 
	TenDDC NVARCHAR(100), 
	Thanhpho NVARCHAR(20)
)
CREATE TABLE LOTRINH(
	MaNoiDi VARCHAR(5) FOREIGN KEY REFERENCES DIEMDUNGCHAN(MaDDC), 
	MaNoiDen VARCHAR(5) FOREIGN KEY REFERENCES DIEMDUNGCHAN(MaDDC),
	CONSTRAINT PK_LT PRIMARY KEY (MaNoiDi, MaNoiDen)
)
CREATE TABLE LOTRINH_TOUR(
	MaTour VARCHAR(3) FOREIGN KEY REFERENCES TOUR(MaTour), 
	MaNoiDi VARCHAR(5), 
	MaNoiDen VARCHAR(5), 
	SongayO INT, 
	SongaydicuaPT INT,
	LoaiPhuongtien NVARCHAR(11),	
	LoaiKhachsan NVARCHAR(5)
	CONSTRAINT PK_LT_T PRIMARY KEY (MaTour, MaNoiDi, MaNoiDen)
)
CREATE TABLE NHANVIENHDDL(
	MaNVHDDL VARCHAR(5) PRIMARY KEY, 
	TenNV NVARCHAR(40), 
	NgaysinhNV DATE, 
	PhaiNV NVARCHAR(3), 
	DiachiNV NVARCHAR(10),
	DienthoaiNV NVARCHAR(11)
)
CREATE TABLE CHUYEN(
	MaChuyen NVARCHAR(5) PRIMARY KEY, 
	Tenchuyen NVARCHAR(25), 
	NgaydiCuaChuyen DATE, 
	MaNVHDDL VARCHAR(5) FOREIGN KEY REFERENCES NHANVIENHDDL(MaNVHDDL),
	MaTour VARCHAR(3) FOREIGN KEY REFERENCES TOUR(MaTour)
)
CREATE TABLE HOPDONG_NV(
    SoHD VARCHAR(5) FOREIGN KEY REFERENCES HOPDONG(SoHD),
    MaNVHDDL VARCHAR(5) FOREIGN KEY REFERENCES NHANVIENHDDL(MaNVHDDL),
    NoidungHD_NV NVARCHAR(100),
    CONSTRAINT PK_HD_NV PRIMARY KEY (SoHD, MaNVHDDL)
);
